import type { Shop, Product, TownEvent } from "./types"

export const shops: Shop[] = [
  {
    id: "shop-mori",
    name: "森のパン工房",
    owner: "森田 めぐみ",
    category: "食品",
    town: "みどり町",
    tagline: "薪窯で焼く、素朴な田舎パン",
    description:
      "毎朝4時から薪窯に火を入れ、地元の小麦と天然酵母だけで焼き上げています。町の朝ごはんを支える小さなパン屋さんです。",
    emoji: "🍞",
    color: "#e8842f",
    rating: 4.8,
    established: "2009年",
  },
  {
    id: "shop-tetsu",
    name: "てつ工房ボルタ",
    owner: "鉄川 剛",
    category: "工芸",
    town: "こうば通り",
    tagline: "ねじとボルトのちいさな鉄の仲間たち",
    description:
      "廃材のボルトやナットに命を吹き込む金属アート工房。ひとつひとつ手作業で表情をつけた、愛らしい鉄のキャラクターたちが人気です。",
    emoji: "🔩",
    color: "#8a8a8a",
    rating: 4.9,
    established: "2015年",
  },
  {
    id: "shop-hana",
    name: "花と緑のはなみち",
    owner: "花房 さくら",
    category: "花・緑",
    town: "みどり町",
    tagline: "暮らしにそっと寄りそう植物たち",
    description:
      "町の花屋さん。季節の花束から育てやすい観葉植物まで、暮らしを彩る緑をお届けします。ラッピングも無料です。",
    emoji: "🌷",
    color: "#d4699a",
    rating: 4.7,
    established: "2012年",
  },
  {
    id: "shop-yaki",
    name: "やきもの ひより窯",
    owner: "陶山 ひより",
    category: "工芸",
    town: "やまて坂",
    tagline: "毎日使いたくなる、手びねりの器",
    description:
      "登り窯で焼く温かみのある器を作っています。ぽってりとした手触りと、料理を引き立てる素朴な色合いが自慢です。",
    emoji: "🏺",
    color: "#b5764a",
    rating: 4.6,
    established: "2018年",
  },
  {
    id: "shop-cafe",
    name: "喫茶ことり",
    owner: "小鳥遊 かなえ",
    category: "喫茶",
    town: "えき前商店街",
    tagline: "町の休憩所、まったり自家焙煎珈琲",
    description:
      "自家焙煎の珈琲豆と手作り焼き菓子のお店。おうちでも喫茶店の味を楽しめるドリップバッグやクッキーを販売しています。",
    emoji: "☕",
    color: "#7a5c3e",
    rating: 4.8,
    established: "2007年",
  },
  {
    id: "shop-zakka",
    name: "雑貨と暮らし tsumugi",
    owner: "紬 ゆい",
    category: "雑貨",
    town: "えき前商店街",
    tagline: "つくり手の顔が見える、小さな道具たち",
    description:
      "町の作家さんが手がける布小物や木工雑貨をセレクト。長く愛せる、暮らしの相棒になる道具を集めました。",
    emoji: "🧺",
    color: "#5b8c7b",
    rating: 4.5,
    established: "2020年",
  },
]

export const products: Product[] = [
  // 森のパン工房
  {
    id: "p-pain",
    shopId: "shop-mori",
    name: "薪窯の田舎パン（ハーフ）",
    price: 480,
    description: "外はパリッと、中はもっちり。噛むほど小麦の甘みが広がります。",
    emoji: "🍞",
    tags: ["天然酵母", "国産小麦"],
    soldCount: 1280,
    last30DaysSold: 143,
  },
  {
    id: "p-croissant",
    shopId: "shop-mori",
    name: "発酵バターのクロワッサン（3個）",
    price: 720,
    description: "何層にも重ねた生地とバターの香り。朝ごはんの特別な一枚。",
    emoji: "🥐",
    tags: ["人気", "冷凍発送"],
    soldCount: 960,
    last30DaysSold: 112,
  },
  {
    id: "p-jam",
    shopId: "shop-mori",
    name: "町の果実の手づくりジャム",
    price: 650,
    description: "近くの農園の果実を煮詰めた季節のジャム。パンのおともに。",
    emoji: "🍓",
    tags: ["季節限定"],
    soldCount: 540,
    last30DaysSold: 58,
  },
  // てつ工房ボルタ
  {
    id: "p-volta",
    shopId: "shop-tetsu",
    name: "ボルタくん（六角ボルトの妖精）",
    price: 2800,
    description: "六角ボルトの頭がチャームポイント。机の上でそっと応援してくれます。",
    emoji: "🔩",
    tags: ["一点物", "手作り"],
    soldCount: 320,
    last30DaysSold: 38,
  },
  {
    id: "p-natty",
    shopId: "shop-tetsu",
    name: "ナッティちゃん（ナットの相棒）",
    price: 2600,
    description: "皿ねじとナットで作った、まるいフォルムの愛らしい仲間。",
    emoji: "⚙️",
    tags: ["一点物", "手作り"],
    soldCount: 410,
    last30DaysSold: 51,
  },
  {
    id: "p-keyring",
    shopId: "shop-tetsu",
    name: "鉄のミニチャーム キーリング",
    price: 1200,
    description: "カバンにつけられる小さな鉄の仲間。毎日をちょっと楽しく。",
    emoji: "🗝️",
    tags: ["ギフト"],
    soldCount: 780,
    last30DaysSold: 96,
  },
  // 花と緑のはなみち
  {
    id: "p-bouquet",
    shopId: "shop-hana",
    name: "季節のおまかせ花束",
    price: 3300,
    description: "その日いちばん元気な花で仕立てるブーケ。ラッピング無料。",
    emoji: "💐",
    tags: ["ギフト", "当日発送"],
    soldCount: 650,
    last30DaysSold: 72,
  },
  {
    id: "p-plant",
    shopId: "shop-hana",
    name: "育てやすい観葉植物 ポトス",
    price: 1800,
    description: "初めてでも安心。お部屋にひとつ、みどりの相棒を。",
    emoji: "🪴",
    tags: ["初心者向け"],
    soldCount: 890,
    last30DaysSold: 108,
  },
  {
    id: "p-dryflower",
    shopId: "shop-hana",
    name: "ドライフラワーのスワッグ",
    price: 2400,
    description: "壁にかけるだけで絵になる、やさしい色合いの花束。",
    emoji: "🌾",
    tags: ["長持ち"],
    soldCount: 470,
    last30DaysSold: 49,
  },
  // ひより窯
  {
    id: "p-mug",
    shopId: "shop-yaki",
    name: "手びねりのマグカップ",
    price: 2900,
    description: "手になじむぽってりフォルム。毎日の珈琲時間にどうぞ。",
    emoji: "☕",
    tags: ["電子レンジ可"],
    soldCount: 560,
    last30DaysSold: 66,
  },
  {
    id: "p-plate",
    shopId: "shop-yaki",
    name: "取り皿 五寸（2枚組）",
    price: 3600,
    description: "料理を引き立てる素朴な色合い。和洋どちらにも。",
    emoji: "🍽️",
    tags: ["ペア"],
    soldCount: 380,
    last30DaysSold: 44,
  },
  {
    id: "p-vase",
    shopId: "shop-yaki",
    name: "一輪挿しの花器",
    price: 2200,
    description: "摘んだ花を一輪。窓辺にそっと飾りたい小さな器。",
    emoji: "🏺",
    tags: ["新作"],
    soldCount: 240,
    last30DaysSold: 29,
  },
  // 喫茶ことり
  {
    id: "p-drip",
    shopId: "shop-cafe",
    name: "自家焙煎ドリップバッグ（10袋）",
    price: 1600,
    description: "お店の味をおうちで。深煎りのまろやかなブレンド。",
    emoji: "☕",
    tags: ["人気", "自家焙煎"],
    soldCount: 1420,
    last30DaysSold: 186,
  },
  {
    id: "p-cookie",
    shopId: "shop-cafe",
    name: "手作り焼き菓子の詰め合わせ",
    price: 1980,
    description: "クッキーとパウンドの詰め合わせ。珈琲のおともに。",
    emoji: "🍪",
    tags: ["ギフト"],
    soldCount: 820,
    last30DaysSold: 104,
  },
  {
    id: "p-beans",
    shopId: "shop-cafe",
    name: "季節のスペシャルティ豆 200g",
    price: 1350,
    description: "季節ごとに変わるとっておきの豆。挽き方も選べます。",
    emoji: "🫘",
    tags: ["季節限定"],
    soldCount: 610,
    last30DaysSold: 73,
  },
  // tsumugi
  {
    id: "p-bag",
    shopId: "shop-zakka",
    name: "作家さんの帆布トートバッグ",
    price: 4200,
    description: "丈夫でくたっと馴染む帆布。長く付き合える相棒に。",
    emoji: "👜",
    tags: ["人気", "手作り"],
    soldCount: 730,
    last30DaysSold: 91,
  },
  {
    id: "p-spoon",
    shopId: "shop-zakka",
    name: "木のカトラリー スプーン＆フォーク",
    price: 2600,
    description: "口当たりやさしい木のカトラリー。毎日の食卓に温もりを。",
    emoji: "🥄",
    tags: ["木工"],
    soldCount: 450,
    last30DaysSold: 57,
  },
  {
    id: "p-towel",
    shopId: "shop-zakka",
    name: "やわらか蚊帳生地のふきん（3枚）",
    price: 1100,
    description: "使うほどにやわらかく。台所仕事が楽しくなるふきん。",
    emoji: "🧻",
    tags: ["日用品"],
    soldCount: 990,
    last30DaysSold: 126,
  },
]

export const townEvents: TownEvent[] = [
  {
    id: "ev-1",
    date: "5.18",
    weekday: "土",
    title: "みどり町 朝市マルシェ",
    location: "みどり町 中央公園",
    description: "町のお店が大集合。焼きたてパンや採れたて野菜、手仕事の雑貨が並びます。",
    tag: "マルシェ",
    url: "https://example.com/events/asaichi",
  },
  {
    id: "ev-2",
    date: "5.25",
    weekday: "土",
    title: "鉄のキャラクター工作ワークショップ",
    location: "こうば通り てつ工房ボルタ",
    description: "ボルタ職人と一緒に、自分だけの鉄の仲間を作ろう。お子さまも参加できます。",
    tag: "ワークショップ",
    url: "https://example.com/events/volta-ws",
  },
  {
    id: "ev-3",
    date: "6.1",
    weekday: "日",
    title: "喫茶ことり 珈琲の淹れ方教室",
    location: "えき前商店街 喫茶ことり",
    description: "自家焙煎の豆を使って、おうちでおいしく淹れるコツを学べます。試飲つき。",
    tag: "教室",
    url: "https://example.com/events/coffee",
  },
  {
    id: "ev-4",
    date: "6.8",
    weekday: "日",
    title: "やまて坂 陶器市",
    location: "やまて坂 商店街一帯",
    description: "町の窯元が集まる年に一度の陶器市。掘り出し物の器に出会えるかも。",
    tag: "陶器市",
    url: "https://example.com/events/tokiichi",
  },
]

export function getShop(id: string): Shop | undefined {
  return shops.find((s) => s.id === id)
}

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function formatYen(n: number): string {
  return "¥" + n.toLocaleString("ja-JP")
}
